version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: voiceowl-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: voiceowl
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
